class _AttributeString(str): ...

def local(command, capture=False, shell=None) -> _AttributeString: ...

def run(command, shell=True, pty=True, combine_stderr=None, quiet=False,
    warn_only=False, stdout=None, stderr=None, timeout=None, shell_escape=None,
    capture_buffer_size=None) -> _AttributeString: ...
