# Stubs for fabric.api (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from context_managers import (cd, hide, settings, show, path, prefix,
    lcd, quiet, warn_only, remote_tunnel, shell_env)
from decorators import (hosts, roles, runs_once, with_settings, task,
        serial, parallel)
from operations import require, prompt, put, get, run, sudo, local, reboot, open_shell
from state import env, output
from utils import abort, warn, puts, fastprint
from tasks import execute

